.. _recover_retry_times_IO:

yr.InvokeOptions.recover_retry_times
----------------------------------------------

.. py:attribute:: InvokeOptions.recover_retry_times
   :type: int
   :value: 0

   实例恢复次数（当实例异常退出时，实例将自动恢复到最新状态）。如果值为 0，则实例在异常退出时不会自动恢复。