.. _exception_ObjectRef:

yr.object_ref.ObjectRef.exception
------------------------------------------------

.. py:method:: ObjectRef.exception()

    如果异常不为 None，则抛出异常。
